micronaut:
  application:
    name: micronautguide
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5433/ciab`}
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:admin}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}


